/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.net.URL;
import jaco.mp3.player.MP3Player;
import java.io.File;
/**
 *
 * @author HNDRWN
 */
public class MainHijaiyah extends javax.swing.JPanel {

    public String url = "";
    /**
     * Creates new form NewJPanel
     */
    public MainHijaiyah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new app.Class1();
        alif = new javax.swing.JButton();
        bak = new javax.swing.JButton();
        tak = new javax.swing.JButton();
        tsak = new javax.swing.JButton();
        jim = new javax.swing.JButton();
        hak = new javax.swing.JButton();
        khok = new javax.swing.JButton();
        dal = new javax.swing.JButton();
        dzal = new javax.swing.JButton();
        rok = new javax.swing.JButton();
        zak = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        syin = new javax.swing.JButton();
        shod = new javax.swing.JButton();
        dhlod = new javax.swing.JButton();
        thok = new javax.swing.JButton();
        zok = new javax.swing.JButton();
        ain = new javax.swing.JButton();
        gha = new javax.swing.JButton();
        fa = new javax.swing.JButton();
        qaf = new javax.swing.JButton();
        kaf = new javax.swing.JButton();
        lam = new javax.swing.JButton();
        mim = new javax.swing.JButton();
        nun = new javax.swing.JButton();
        wa = new javax.swing.JButton();
        ha = new javax.swing.JButton();
        hamzah = new javax.swing.JButton();
        ya = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(730, 575));

        alif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/01.png"))); // NOI18N
        alif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alifActionPerformed(evt);
            }
        });

        bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/02.png"))); // NOI18N
        bak.setActionCommand("jButton2");
        bak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakActionPerformed(evt);
            }
        });

        tak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/03.png"))); // NOI18N
        tak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takActionPerformed(evt);
            }
        });

        tsak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/04.png"))); // NOI18N
        tsak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsakActionPerformed(evt);
            }
        });

        jim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/05.png"))); // NOI18N
        jim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimActionPerformed(evt);
            }
        });

        hak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/06.png"))); // NOI18N
        hak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakActionPerformed(evt);
            }
        });

        khok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/07.png"))); // NOI18N
        khok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khokActionPerformed(evt);
            }
        });

        dal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/08.png"))); // NOI18N
        dal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dalActionPerformed(evt);
            }
        });

        dzal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/09.png"))); // NOI18N
        dzal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dzalActionPerformed(evt);
            }
        });

        rok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/10.png"))); // NOI18N
        rok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rokActionPerformed(evt);
            }
        });

        zak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/11.png"))); // NOI18N
        zak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zakActionPerformed(evt);
            }
        });

        sin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/12.png"))); // NOI18N
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        syin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/13.png"))); // NOI18N
        syin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syinActionPerformed(evt);
            }
        });

        shod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/14.png"))); // NOI18N
        shod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shodActionPerformed(evt);
            }
        });

        dhlod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/15.png"))); // NOI18N
        dhlod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhlodActionPerformed(evt);
            }
        });

        thok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/16.png"))); // NOI18N
        thok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thokActionPerformed(evt);
            }
        });

        zok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/17.png"))); // NOI18N
        zok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zokActionPerformed(evt);
            }
        });

        ain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/18.png"))); // NOI18N
        ain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ainActionPerformed(evt);
            }
        });

        gha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/19.png"))); // NOI18N
        gha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghaActionPerformed(evt);
            }
        });

        fa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/20.png"))); // NOI18N
        fa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faActionPerformed(evt);
            }
        });

        qaf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/21.png"))); // NOI18N
        qaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qafActionPerformed(evt);
            }
        });

        kaf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/22.png"))); // NOI18N
        kaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kafActionPerformed(evt);
            }
        });

        lam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/23.png"))); // NOI18N
        lam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamActionPerformed(evt);
            }
        });

        mim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/24.png"))); // NOI18N
        mim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimActionPerformed(evt);
            }
        });

        nun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/25.png"))); // NOI18N
        nun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nunActionPerformed(evt);
            }
        });

        wa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/26.png"))); // NOI18N
        wa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waActionPerformed(evt);
            }
        });

        ha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/27.png"))); // NOI18N
        ha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haActionPerformed(evt);
            }
        });

        hamzah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/28.png"))); // NOI18N
        hamzah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamzahActionPerformed(evt);
            }
        });

        ya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/29.png"))); // NOI18N
        ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sin)
                            .addComponent(ain)
                            .addComponent(mim)
                            .addComponent(hak))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zak)
                            .addComponent(zok)
                            .addComponent(lam)
                            .addComponent(jim)))
                    .addComponent(ya))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rok, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tsak, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thok, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kaf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hamzah, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tak, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dzal, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dhlod, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(qaf, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(ha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wa)
                    .addComponent(dal)
                    .addComponent(bak)
                    .addComponent(shod)
                    .addComponent(fa))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(syin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(khok))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(alif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tak, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bak, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tsak, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hak, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jim))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sin)
                    .addComponent(zak)
                    .addComponent(rok)
                    .addComponent(dzal)
                    .addComponent(dal)
                    .addComponent(khok))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dhlod)
                    .addComponent(shod)
                    .addComponent(thok)
                    .addComponent(syin)
                    .addComponent(ain)
                    .addComponent(zok))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gha)
                            .addComponent(fa)
                            .addComponent(qaf)
                            .addComponent(kaf)
                            .addComponent(mim))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nun)
                                    .addComponent(wa)
                                    .addComponent(ha)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hamzah, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ya, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addComponent(lam))
                .addGap(140, 140, 140))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alifActionPerformed
        url = "src\\audio\\01.mp3";
        MP3Player alif = new MP3Player(new File(url));
        alif.stop();
        alif.play();
    }//GEN-LAST:event_alifActionPerformed

    private void bakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakActionPerformed
        url = "src\\audio\\02.mp3";
        MP3Player bak = new MP3Player(new File(url));
        bak.stop();
        bak.play();
    }//GEN-LAST:event_bakActionPerformed

    private void takActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takActionPerformed
        url = "src\\audio\\03.mp3";
        MP3Player tak = new MP3Player(new File(url));
        tak.stop();
        tak.play();
    }//GEN-LAST:event_takActionPerformed

    private void tsakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsakActionPerformed
        url = "src\\audio\\04.mp3";
        MP3Player tsak = new MP3Player(new File(url));
        tsak.stop();
        tsak.play();
    }//GEN-LAST:event_tsakActionPerformed

    private void jimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimActionPerformed
        url = "src\\audio\\05.mp3";
        MP3Player jim = new MP3Player(new File(url));
        jim.stop();
        jim.play();
    }//GEN-LAST:event_jimActionPerformed

    private void hakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakActionPerformed
        url = "src\\audio\\06.mp3";
        MP3Player hak = new MP3Player(new File(url));
        hak.stop();
        hak.play();
    }//GEN-LAST:event_hakActionPerformed

    private void khokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khokActionPerformed
        url = "src\\audio\\07.mp3";
        MP3Player khok = new MP3Player(new File(url));
        khok.stop();
        khok.play();
    }//GEN-LAST:event_khokActionPerformed

    private void dalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dalActionPerformed
        url = "src\\audio\\08.mp3";
        MP3Player dal = new MP3Player(new File(url));
        dal.stop();
        dal.play();
    }//GEN-LAST:event_dalActionPerformed

    private void dzalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dzalActionPerformed
        url = "src\\audio\\09.mp3";
        MP3Player dzal = new MP3Player(new File(url));
        dzal.stop();
        dzal.play();
    }//GEN-LAST:event_dzalActionPerformed

    private void rokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rokActionPerformed
        url = "src\\audio\\10.mp3";
        MP3Player rok = new MP3Player(new File(url));
        rok.stop();
        rok.play();
    }//GEN-LAST:event_rokActionPerformed

    private void zakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zakActionPerformed
        url = "src\\audio\\11.mp3";
        MP3Player zak = new MP3Player(new File(url));
        zak.stop();
        zak.play();
    }//GEN-LAST:event_zakActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        url = "src\\audio\\12.mp3";
        MP3Player sin = new MP3Player(new File(url));
        sin.stop();
        sin.play();
    }//GEN-LAST:event_sinActionPerformed

    private void syinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syinActionPerformed
        url = "src\\audio\\13.mp3";
        MP3Player syin = new MP3Player(new File(url));
        syin.stop();
        syin.play();
    }//GEN-LAST:event_syinActionPerformed

    private void shodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shodActionPerformed
        url = "src\\audio\\14.mp3";
        MP3Player shod = new MP3Player(new File(url));
        shod.stop();
        shod.play();
    }//GEN-LAST:event_shodActionPerformed

    private void dhlodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhlodActionPerformed
        url = "src\\audio\\15.mp3";
        MP3Player dhlod = new MP3Player(new File(url));
        dhlod.stop();
        dhlod.play();
    }//GEN-LAST:event_dhlodActionPerformed

    private void thokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thokActionPerformed
        url = "src\\audio\\16.mp3";
        MP3Player thok = new MP3Player(new File(url));
        thok.stop();
        thok.play();
    }//GEN-LAST:event_thokActionPerformed

    private void zokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zokActionPerformed
        url = "src\\audio\\17.mp3";
        MP3Player zok = new MP3Player(new File(url));
        zok.stop();
        zok.play();
    }//GEN-LAST:event_zokActionPerformed

    private void ainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ainActionPerformed
        url = "src\\audio\\18.mp3";
        MP3Player ain = new MP3Player(new File(url));
        ain.stop();
        ain.play();
    }//GEN-LAST:event_ainActionPerformed

    private void ghaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghaActionPerformed
        url = "src\\audio\\19.mp3";
        MP3Player gha = new MP3Player(new File(url));
        gha.stop();
        gha.play();
    }//GEN-LAST:event_ghaActionPerformed

    private void faActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faActionPerformed
        url = "src\\audio\\20.mp3";
        MP3Player fa = new MP3Player(new File(url));
        fa.stop();
        fa.play();
    }//GEN-LAST:event_faActionPerformed

    private void qafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qafActionPerformed
        url = "src\\audio\\21.mp3";
        MP3Player qaf = new MP3Player(new File(url));
        qaf.stop();
        qaf.play();
    }//GEN-LAST:event_qafActionPerformed

    private void kafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kafActionPerformed
        url = "src\\audio\\22.mp3";
        MP3Player kaf = new MP3Player(new File(url));
        kaf.stop();
        kaf.play();
    }//GEN-LAST:event_kafActionPerformed

    private void lamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamActionPerformed
        url = "src\\audio\\23.mp3";
        MP3Player lam = new MP3Player(new File(url));
        lam.stop();
        lam.play();
    }//GEN-LAST:event_lamActionPerformed

    private void mimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimActionPerformed
        url = "src\\audio\\24.mp3";
        MP3Player mim = new MP3Player(new File(url));
        mim.stop();
        mim.play();
    }//GEN-LAST:event_mimActionPerformed

    private void nunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nunActionPerformed
        url = "src\\audio\\25.mp3";
        MP3Player nun = new MP3Player(new File(url));
        nun.stop();
        nun.play();
    }//GEN-LAST:event_nunActionPerformed

    private void waActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waActionPerformed
        url = "src\\audio\\26.mp3";
        MP3Player wa = new MP3Player(new File(url));
        wa.stop();
        wa.play();
    }//GEN-LAST:event_waActionPerformed

    private void haActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haActionPerformed
        url = "src\\audio\\27.mp3";
        MP3Player ha = new MP3Player(new File(url));
        ha.stop();
        ha.play();
    }//GEN-LAST:event_haActionPerformed

    private void hamzahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamzahActionPerformed
        url = "src\\audio\\28.mp3";
        MP3Player hamzah = new MP3Player(new File(url));
        hamzah.stop();
        hamzah.play();
    }//GEN-LAST:event_hamzahActionPerformed

    private void yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaActionPerformed
        url = "src\\audio\\29.mp3";
        MP3Player ya = new MP3Player(new File(url));
        ya.stop();
        ya.play();
    }//GEN-LAST:event_yaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ain;
    private javax.swing.JButton alif;
    private javax.swing.JButton bak;
    private javax.swing.JButton dal;
    private javax.swing.JButton dhlod;
    private javax.swing.JButton dzal;
    private javax.swing.JButton fa;
    private javax.swing.JButton gha;
    private javax.swing.JButton ha;
    private javax.swing.JButton hak;
    private javax.swing.JButton hamzah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jim;
    private javax.swing.JButton kaf;
    private javax.swing.JButton khok;
    private javax.swing.JButton lam;
    private javax.swing.JButton mim;
    private javax.swing.JButton nun;
    private javax.swing.JButton qaf;
    private javax.swing.JButton rok;
    private javax.swing.JButton shod;
    private javax.swing.JButton sin;
    private javax.swing.JButton syin;
    private javax.swing.JButton tak;
    private javax.swing.JButton thok;
    private javax.swing.JButton tsak;
    private javax.swing.JButton wa;
    private javax.swing.JButton ya;
    private javax.swing.JButton zak;
    private javax.swing.JButton zok;
    // End of variables declaration//GEN-END:variables
}
